MyDjango/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include("web.urls")),                # 默认前台大堂点餐端
    path('myadmin/', include("myadmin.urls")),     # 后台管理端

]

web/urls.py
# myobject/web/urls.py

from django.urls import path

from web.views import index,home

urlpatterns = [
   path('', index.index, name="home"),
   #用户登录
   path('login/', index.login, name="web_login"),
   # 图片验证码
   path('image/code/', index.image_code, name="web_image_code"),
   #短信登录账户
   path('login/sms/', index.login_sms, name="web_login_sms"),
   #注册账户
   path('register/', index.register, name="web_register"),
   #发送短信
   path('send/sms/', index.send_sms, name="web_send_sms"),#短信
   # 登录首页
   path('index/', home.index, name="index"),

]

web/models.py
from django.db import models

# Create your models here.
class UserInfo(models.Model):
    username = models.CharField(verbose_name='用户名', max_length=32)
    email = models.EmailField(verbose_name='邮件', max_length=32)
    mobile_phone = models.CharField(verbose_name='手机号', max_length=32)
    password = models.CharField(verbose_name='密码', max_length=32)

web/views/home.py
from django.shortcuts import render

def index(request):
    return render(request,'web/index/home.html')

templates/web/index/home.html
{% extends 'web/basic.html' %}
{% load static %}

{% block title %}后台主页 {% endblock %}


{% block content %}

    <h1>后台主页</h1>

{% endblock %}

templates/web/index/index.html
{% extends 'web/basic.html' %}
{% load static %}


{% block title %}{% endblock %}
{% block css %}{% endblock %}


{% block content %}
    <div class="navbar-brand "><h1>账户注册</h1></div>
{% endblock %}

{% block js %}{% endblock %}

templates/web/index/login.html
{% extends 'web/basic.html' %}
{% load static %}

{% block title %}用户登录 {% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'web/css/account.css' %}">
    <style>
        .error-msg{
            color: red;
            position: absolute;
            font-size: 13px;
        }
    </style>
{% endblock %}


{% block content %}
    <div class="account">
    <div class="title">用户登录</div>
        <form method="post" novalidate>
            {% csrf_token %}
            {% for field in form %}
                {% if field.name == 'code' %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}:</label>
                        <div class="row">
                            <div class="col-md-7">{{ field }}<span class="error-msg">{{ field.errors.0 }}</span></div>
                            <div class="col-md-5"><img src="{% url 'web_image_code' %}" id="imageCode"></div>
                        </div>
                    </div>
                {% else %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}:</label>
                        {{ field }}
                        <span class="error-msg">{{ field.errors.0 }}</span>
                    </div>
                {% endif %}
            {% endfor %}
            <div>
                <div style="float:right">
                    <a href="{% url 'web_login_sms' %}">短信验证码登录</a>
                </div>
            </div>

              <div class="row">
                    <!-- /.col -->
                    <div class="col-xs-3">
                      <button id="submit" type="submit"  class="btn btn-primary btn-block btn-flat">登录</button>
                    </div>
              </div>
        </form>
    </div>


{% endblock %}


{% block js %}
    <script>
        $(function (){
            $('#imageCode').click(function (){
                var oldSrc = $(this).attr('src');
                $(this).attr('src',oldSrc+"?");//index/?name=123
            })
        })
    </script>
{% endblock %}

templates/web/index/login_sms.html
{% extends 'web/basic.html' %}
{% load static %}

{% block title %}用户短信登录 {% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'web/css/account.css' %}">
    <style>
        .error-msg{
            color: red;
            position: absolute;
            font-size: 13px;
        }
    </style>
{% endblock %}


{% block content %}
    <div class="account">
    <div class="title">用户短信登录</div>
        <form id = "smsForm" method="post" novalidate>
            {% csrf_token %}
            {% for field in form %}
                {% if field.name == 'code' %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}:</label>
                        <div class="row">
                            <div class="col-md-7">{{ field }}<span class="error-msg"></span></div>
                            <div class="col-md-5"><input id="btnsms" type="button"  class="btn btn-default" value="点击获取验证码"></div>
                        </div>
                    </div>
                {% else %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}:</label>
                        {{ field }}
                        <span class="error-msg"></span>
                    </div>
                {% endif %}
            {% endfor %}

              <div class="row">
                    <!-- /.col -->
                    <div class="col-xs-3">
                      <button id="btnSubmit" type="submit"  class="btn btn-primary btn-block btn-flat">登录</button>
                    </div>
              </div>
        </form>
    </div>


{% endblock %}


{% block js %}
    <script>
        //页面框架加载完成之后自动执行函数
        $(function (){
            bindclickbtnsms();
            bindClickSubmit();
        });

        /*
        点击登录
        */
        function bindClickSubmit() {
            $('#btnSubmit').click(function () {
                $('.error-msg').empty();
                // 收集表单中的数据（找到每一个字段）$('#regForm').serialize()
                // 数据ajax发送到后台
                $.ajax({
                    url: "{% url 'web_login_sms' %}",
                    type: "POST",
                    data: $('#smsForm').serialize(), // 所有字段数据 + csrf token
                    dataType: "JSON",
                    success: function (res) {
                        if(res.status){
                            location.href = res.data;
                        }else{
                            $.each(res.error, function (key, value) {
                                $("#id_" + key).next().text(value[0]);
                            })
                        }
                    }
                })
            })
        }

        /*
        点击获取验证码的按钮绑定事件
        * */
        function bindclickbtnsms(){
            $('#btnsms').click(function (){
                //获取用户输入的手机号
                //找到输入框的ID，根据ID获取值，如何找到手机号的那个ID？

                var mobilePhone =$('#id_mobile_phone').val();

                {#alart($('#id_mobile_phone').val());#}
                //发送ajax请求，把手机号发送过去
                $.ajax({
                    url:"{% url 'web_send_sms' %}",//要提交的地址
                    type:"GET",
                    data:{mobile_phone: mobilePhone ,tpl: "login"},
                    dataType: "JSON",// 将服务端返回的数据反序列化为字典
                    success:function (res){
                        //ajax请求发送成功之后，自动执行的函数；res就是后端返回的值
                        if (res.status){
                            {#console.log('发送成功，倒计时')#}
                            {#console.log(res)#}
                            sendSmsRemind();
                        }   else {
                             // 错误信息
                            // console.log(res); // {status:False, error:{ mobile_phone: ["错误信息"，],code: ["错误信息"，] }  }
                            $.each(res.error, function (key, value){
                                $("#id_"+ key).next().text(value[0]);
                            })
                        }
                    }
                })
            })
        }


        /*
        倒计时
        */
        function sendSmsRemind() {
            var $smsBtn = $('#btnsms');

            $smsBtn.prop('disabled',true); // 禁用

            var time = 60;
            var remind = setInterval(function () {
                $smsBtn.val(time + '秒重新发送');
                time = time - 1;
                if (time < 1) {
                    clearInterval(remind);
                    $smsBtn.val('点击获取验证码').prop('disabled', false);
                }
            }, 1000)
        }
    </script>
{% endblock %}

templates/web/index/register.html
{% extends 'web/basic.html' %}
{% load static %}

{% block title %} 用户注册 {% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'web/css/account.css' %}">
    <style>
        .error-msg{
            color: red;
            position: absolute;
            font-size: 13px;
        }
    </style>
{% endblock %}


{% block content %}
    <div class="account">
    <div class="title">用户注册</div>
        <form id = "regForm" method="post" novalidate>
            {% csrf_token %}
            {% for field in form %}
                {% if field.name == 'code' %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}:</label>
                        <div class="row">
                            <div class="col-md-7">{{ field }}<span class="error-msg"></span></div>
                            <div class="col-md-5"><input id="btnsms" type="button"  class="btn btn-default" value="点击获取验证码"></div>
                        </div>
                    </div>
                {% else %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}:</label>
                        {{ field }}
                        <span class="error-msg"></span>
                    </div>
                {% endif %}
            {% endfor %}

              <div class="row">
                <div class="col-xs-8">
                  <div class="checkbox icheck">
                    <label>
                      <input type="checkbox"> 我同意 <a href="#">条约</a>
                    </label>
                  </div>
                </div>
                    <!-- /.col -->
                    <div class="col-xs-4">
                      <button id="btnSubmit" type="button"  class="btn btn-primary btn-block btn-flat">注册</button>
                    </div>
              </div>
        </form>
    </div>


{% endblock %}


{% block js %}
    <script>
        //页面框架加载完成之后自动执行函数
        $(function (){
            bindclickbtnsms();
            bindClickSubmit();
        });
        /*
        点击提交（注册）
        */
        /***
         ***/
        function bindClickSubmit() {
            $('#btnSubmit').click(function () {
                $('.error-msg').empty();
                // 收集表单中的数据（找到每一个字段）$('#regForm').serialize()
                // 数据ajax发送到后台
                $.ajax({
                    url: "{% url 'web_register' %}",
                    type: "POST",
                    data: $('#regForm').serialize(), // 所有字段数据 + csrf token
                    dataType: "JSON",
                    success: function (res) {
                        if(res.status){
                            location.href = res.data;
                        }else{
                            $.each(res.error, function (key, value) {
                                $("#id_" + key).next().text(value[0]);
                            })
                        }
                    }
                })
            })
        }

        /*
        点击获取验证码的按钮绑定事件
        * */
        function bindclickbtnsms(){
            $('#btnsms').click(function (){
                //获取用户输入的手机号
                //找到输入框的ID，根据ID获取值，如何找到手机号的那个ID？

                var mobilePhone =$('#id_mobile_phone').val();

                {#alart($('#id_mobile_phone').val());#}
                //发送ajax请求，把手机号发送过去
                $.ajax({
                    url:"{% url 'web_send_sms' %}",//要提交的地址
                    type:"GET",
                    data:{mobile_phone: mobilePhone ,tpl: "register"},
                    dataType: "JSON",// 将服务端返回的数据反序列化为字典
                    success:function (res){
                        //ajax请求发送成功之后，自动执行的函数；res就是后端返回的值
                        if (res.status){
                            {#console.log('发送成功，倒计时')#}
                            {#console.log(res)#}
                            sendSmsRemind();
                        }   else {
                             // 错误信息
                            // console.log(res); // {status:False, error:{ mobile_phone: ["错误信息"，],code: ["错误信息"，] }  }
                            $.each(res.error, function (key, value){
                                $("#id_"+ key).next().text(value[0]);
                            })
                        }
                    }
                })
            })
        }
        /*
        倒计时
        */
        function sendSmsRemind() {
            var $smsBtn = $('#btnsms');

            $smsBtn.prop('disabled',true); // 禁用

            var time = 60;
            var remind = setInterval(function () {
                $smsBtn.val(time + '秒重新发送');
                time = time - 1;
                if (time < 1) {
                    clearInterval(remind);
                    $smsBtn.val('点击获取验证码').prop('disabled', false);
                }
            }, 1000)
        }



    </script>
{% endblock %}